
# 100 numpy exercises
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the initialize.py module, then for each question you can query the answer or an hint with hint(n) or answer(n) for n question number.

### 1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.version.version

'1.18.5'

In [3]:
print(np.__version__)


1.18.5


In [4]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


### 3. Create a null vector of size 10 (★☆☆)

In [5]:
a = np.zeros((10),int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 4. How to find the memory size of any array (★☆☆)

In [18]:
print("bytes:",a.size * a.itemsize)


bytes: 40


### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [25]:
a = np.zeros((10),int)
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])


### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [36]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last) (★☆☆)

In [37]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [41]:
a = np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [49]:
a = np.nonzero([1,2,0,0,4,0])
a

(array([0, 1, 4], dtype=int64),)

### 11. Create a 3x3 identity matrix (★☆☆)

In [58]:
a = np.eye(3,3,0,int)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 12. Create a 3x3x3 array with random values (★☆☆)

In [63]:
a = np.random.random((3,3,3))
a

array([[[0.99943617, 0.51269829, 0.91225834],
        [0.61700795, 0.17554442, 0.94910178],
        [0.50602313, 0.18100454, 0.30052541]],

       [[0.30311533, 0.68410455, 0.73929665],
        [0.42098742, 0.71020904, 0.18057897],
        [0.90544462, 0.87262281, 0.24923252]],

       [[0.82489903, 0.19992333, 0.06349769],
        [0.65553545, 0.9481606 , 0.18594503],
        [0.04812899, 0.81456833, 0.10876964]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [66]:
a = np.random.random((10,10))
a

array([[0.23485722, 0.47817514, 0.26449969, 0.93833386, 0.02002425,
        0.71659359, 0.08302664, 0.46412627, 0.09943224, 0.20942223],
       [0.25939132, 0.76986265, 0.71191949, 0.45610662, 0.73823984,
        0.20456901, 0.49385049, 0.67109117, 0.02968769, 0.43436506],
       [0.7457743 , 0.36379629, 0.50384088, 0.42919485, 0.54132836,
        0.13021694, 0.01987645, 0.22425355, 0.17768546, 0.11604592],
       [0.06914938, 0.35095101, 0.96685081, 0.92156654, 0.53027925,
        0.80668333, 0.53480531, 0.92350867, 0.18501466, 0.90593752],
       [0.4966885 , 0.67183882, 0.44800983, 0.98152579, 0.16710649,
        0.50355795, 0.1368249 , 0.81322508, 0.34448227, 0.48263208],
       [0.52814593, 0.0644801 , 0.3717211 , 0.90791957, 0.65967964,
        0.24868465, 0.21936791, 0.64024091, 0.66009659, 0.94449868],
       [0.77485606, 0.90705019, 0.15036694, 0.14465896, 0.61709205,
        0.19331937, 0.46755031, 0.82796918, 0.75689249, 0.65343705],
       [0.33882593, 0.87559523, 0.6352586

In [69]:
print(np.max(a))
print(np.min(a))

0.981525786120667
0.01987645314551223


### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [72]:
a = np.arange(30)
print(a.mean())

14.5


### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [37]:
a = np.ones((10,5))
a[1:-1,1:-1] = 0
print(a)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [91]:
a = np.arange(0,50)
a = a.reshape(10,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [98]:
a[0::,[0,4]] = 0
a[[0,9],0::] = 0
a


array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  7,  8,  0],
       [ 0, 11, 12, 13,  0],
       [ 0, 16, 17, 18,  0],
       [ 0, 21, 22, 23,  0],
       [ 0, 26, 27, 28,  0],
       [ 0, 31, 32, 33,  0],
       [ 0, 36, 37, 38,  0],
       [ 0, 41, 42, 43,  0],
       [ 0,  0,  0,  0,  0]])

### 17. What is the result of the following expression? (★☆☆)

In [110]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [116]:
a=np.diag(np.arange(1,5),k = -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [118]:
a = np.ones((8,8),int)
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [120]:
a[1::2,::2]= 0
a[::2, 1::2] = 0

In [122]:
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [57]:
print (np.unravel_index(100, (6,7,8)))


(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [26]:
a = [[0,1],[1,0]]
a

[[0, 1], [1, 0]]

In [28]:
a = np.array(a)
a

array([[0, 1],
       [1, 0]])

In [29]:
np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [30]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
a = np.ones((8,8)).astype(int)
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [17]:
x = np.tile(a,(2,2))
x


array([[7, 8, 7, 8],
       [9, 8, 9, 8],
       [3, 5, 3, 5],
       [7, 8, 7, 8],
       [9, 8, 9, 8],
       [3, 5, 3, 5]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [69]:
a = np.random.random((5,5))
a = a.flatten()
a = a * 10
a

array([6.62786784, 1.65705761, 2.67910636, 6.69550923, 5.18520786,
       8.1657116 , 0.40906877, 4.12316657, 6.88770349, 4.84065692,
       9.73084129, 7.56705214, 8.33626205, 7.07539125, 7.08252639,
       7.77964178, 5.63956841, 6.86960605, 7.59935745, 9.28688913,
       3.05330794, 9.83121723, 7.00548344, 4.08934222, 3.49937095])

[[0.20648709 0.55651984 0.28792112 0.90188399 0.54825552]
 [0.46108709 0.4914914  0.23620621 0.23631737 0.29353807]
 [0.75780992 0.12498761 1.         0.26761799 0.        ]
 [0.26305359 0.02044377 0.77226181 0.43419701 0.61144326]
 [0.60952519 0.57836247 0.56597116 0.24606809 0.15929376]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

In [ ]:
colorz = [('r',np.ubyte),['g',np.ubyte])]

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)