## 1D array

In [1]:
array = [0,3,6,9,36,56,66]

In [2]:
type(array)

list

In [2]:
import numpy as np

In [4]:
np_array = np.array(array)

In [5]:
np_array

array([ 0,  3,  6,  9, 36, 56, 66])

In [6]:
type(np_array)

numpy.ndarray

## properties

# dimention

In [9]:
print(f"dimention: {np_array.ndim}") ## dimention of the arrray

ndim: 1


# shape

In [10]:
print(f"shape: {np_array.shape}") ## size of the array of each dimention (row,col)

shape: (7,)


# size

In [11]:
print(f"size: {np_array.size}") ## size of the array

size: 7


# data type

In [12]:
print(f"data type: {np_array.dtype}") ## data type of the element in the array

data type: int32


## 2D array

In [35]:
array2d = [[0,3,6,9],[4,16,32,64],[5,10,15,20]]

In [36]:
np_array2d = np.array(array2d)

In [37]:
type(np_array2d)

numpy.ndarray

In [38]:
print(np_array2d)

[[ 0  3  6  9]
 [ 4 16 32 64]
 [ 5 10 15 20]]


# properties

In [39]:
print(f"dimention: {np_array2d.ndim}")

dimention: 2


In [41]:
print(f"shape: {np_array2d.shape}") ## row and coloumn

shape: (3, 4)


In [43]:
print(f"size: {np_array2d.size}")

size: 12


In [45]:
print(f"data type:{np_array2d.dtype}")

data type:int32


# np.ones((row,col),data type)

In [48]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# np.zeros((row,col),data type)

In [50]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# np.arange(start,stop,step)

In [53]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# np.linspace(start,stop,num = 50,retstep = True) 

In [60]:
np.linspace(1,20,10,retstep = True)

(array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
        11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]),
 2.111111111111111)

# arr = np.array(new array)
# arr.reshape(3,4)

In [76]:
ones = np.ones((3,4),int)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [77]:
ones.reshape(4,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [81]:
arr = np.arange(1,13,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# np.full((row,col),value= x)

In [83]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

# np.eye(row,col,key = 0,data type)

In [90]:
np.eye(3,4,0,int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

# np.random.random((row,col))

In [9]:
np.random.random((3,4))

array([[0.28086539, 0.73666591, 0.18811426, 0.77695958],
       [0.77382199, 0.26992642, 0.53554305, 0.58149021],
       [0.59501009, 0.36475386, 0.91726093, 0.82384388]])

# default_rng(1234)

In [10]:
from numpy.random import default_rng

In [13]:
rng = default_rng(246)

In [14]:
random_arr = rng.random((3,4))

In [16]:
random_arr

array([[0.25241047, 0.31855919, 0.78288238, 0.71969598],
       [0.76868974, 0.21324298, 0.84089393, 0.96889796],
       [0.12970586, 0.17215766, 0.99165005, 0.23770549]])

In [17]:
rng = default_rng(1234)

In [18]:
mean,std_d = 2,0.8

In [19]:
random_array = rng.normal(mean,std_d,(3,4))

In [20]:
random_array

array([[0.71693056, 2.05127993, 2.59271304, 2.12209535],
       [2.69099511, 4.33047938, 0.81694131, 2.75637838],
       [0.66709163, 2.27499567, 1.59004503, 3.05900717]])

In [21]:
random_array.T

array([[0.71693056, 2.69099511, 0.66709163],
       [2.05127993, 4.33047938, 2.27499567],
       [2.59271304, 0.81694131, 1.59004503],
       [2.12209535, 2.75637838, 3.05900717]])

# 1D Array Indexing & Slicing

Indexing & slicing one-dimensional arrays is the same as base Python

array[index] – indexing to access a single element (0-indexed)

array[start:stop:step size] – slicing to access a series of elements (stop is not inclusive)

In [26]:
new_arr = np.arange(5,10)
new_arr

array([5, 6, 7, 8, 9])

In [28]:
new_arr[3] # 4 th index element

8

In [30]:
new_arr[-2] # 2nd last element

8

In [33]:
new_arr[0:3] # Last index is exculded

array([5, 6, 7])

In [34]:
new_arr[::2]

array([5, 7, 9])

In [35]:
new_arr[-1] = 15

In [36]:
new_arr

array([ 5,  6,  7,  8, 15])

In [37]:
new_arr[0:3] = [1,2,3]

In [38]:
new_arr

array([ 1,  2,  3,  8, 15])

# 2D array

Indexing & slicing two-dimensional arrays requires an extra index or slice

array[row index, column index] – indexing to access a single element (0-indexed)

array[start:stop:step_size, start:stop:step_size] – slicing to access a series of elements

In [57]:
array = np.arange(16)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
new_array = array.reshape((4,4))

In [59]:
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
new_array[1]

array([4, 5, 6, 7])

In [63]:
print(new_array[1,2])
print(new_array[1][2])
new_array

6
6


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
new_array[::2,0:3]

array([[ 0,  1,  2],
       [ 8,  9, 10]])

In [85]:
new_array[1: , [0,2]] # 1 no row thaka start kore baki sob row and spacific col no 0 and 2 nia matrix

array([[ 4,  6],
       [ 8, 10],
       [12, 14]])

In [75]:
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
new_array[1:2,1:3] # row 1 er col 1 and 3

array([[5, 6]])

In [92]:
new_array[1,[1,2]] # row 1 er col 1 and 3

array([5, 6])

In [97]:
print(new_array[0:4,2])
print(new_array[[0,1,2,3],2])
# 2 no col er 0,1,2,3 row er value

[ 2  6 10 14]
[ 2  6 10 14]


In [98]:
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
print(new_array[2:4,2:4])
print("__________")
print(new_array[2:,2:])

[[10 11]
 [14 15]]
__________
[[10 11]
 [14 15]]


In [106]:
new_array[1::2,0::2]

array([[ 4,  6],
       [12, 14]])

## Array operation

In [110]:
sales = [[2,4,6,8,10],[3,9,18,21,26]]
sales = np.array(sales)
sales

array([[ 2,  4,  6,  8, 10],
       [ 3,  9, 18, 21, 26]])

In [111]:
sales + 2

array([[ 4,  6,  8, 10, 12],
       [ 5, 11, 20, 23, 28]])

In [115]:
quantity = sales[0,]
prices = sales[1,]
print(quantity)

[ 2  4  6  8 10]


In [114]:
print(prices)

[ 3  9 18 21 26]


In [116]:
quantity * prices

array([  6,  36, 108, 168, 260])